// Dining Menu Data Structure
// This file contains the structured menu data for Dehaati Restaurant

const diningMenu = [
    {
        categoryTitle: "Appetizers",
        hideCategory: false,
        menuItems: [
            {
                title: "Vada Pav",
                description: "Mumbai-style vada pav with chutneys",
                cost: 5.99,
                spiceLevel: "mild",
                region: "Mumbai",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Kothimbir Vadi",
                description: "Snacks made with coriander and besan",
                cost: 6.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Prawns Rava Fry",
                description: "Coastal Maharashtrian semolina-crusted prawns",
                cost: 14.00,
                spiceLevel: "medium",
                region: "Coastal Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Thali",
        hideCategory: false,
        menuItems: [
            {
                title: "Pune Chicken Thali",
                description: "Village style, Spicy, Rustic Chicken Sukkha, Rassa, yellow curry/Alani, solkadi, rice, chapati/Jowar bhakari, Gulab Jamun",
                cost: 24.99,
                spiceLevel: "spicy",
                region: "Pune",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kolhapuri Chicken Thali",
                description: "Chicken Masala, Tambda, pandra solkadi, rice, chapati/Jowar bhakari, Gulab Jamun",
                cost: 25.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kolhapuri Mutton Thali",
                description: "Mutton Masala, Tambda, pandra solkadi, rice, chapati/Jowar bhakari, Gulab Jamun. Make it special: Mutton Lonche/Pickle + Pulav +$5",
                cost: 28.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Egg Thali",
                description: "Egg Malasa, Egg Rassa, Chapati/Bhakri, Solkadi, Rice, Gulab Jamun",
                cost: 23.99,
                spiceLevel: "medium",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Veg Thali",
                description: "Veg Gravy, Dry Vegi, Chapati/Jowar Bhakari, Solkadi, Sweet, Fried Item, Papad/Kurdai, Daal, Rice",
                cost: 19.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Kids Chicken Thali",
                description: "Chapati, Alani rassa, Chicken Masala, SolKadi, Rice, Gulab Jamun",
                cost: 11.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kids Veg Thali",
                description: "Paneer, Chapati, SolKadi, Rice, Gulab Jamun",
                cost: 9.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Plates",
        hideCategory: false,
        menuItems: [
            {
                title: "Pune St Chicken Sukkha",
                description: "Village style spicy dry chicken preparation",
                cost: 15.99,
                spiceLevel: "spicy",
                region: "Pune",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kolhapuri Chicken Masala",
                description: "Spicy Kolhapuri style chicken curry",
                cost: 15.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: true,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kolhapuri Mutton Masala",
                description: "Spicy Kolhapuri style mutton curry",
                cost: 17.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Sides",
        hideCategory: false,
        menuItems: [
            {
                title: "Pune Chicken Rassa",
                description: "Thin spicy chicken curry",
                cost: 5.99,
                spiceLevel: "spicy",
                region: "Pune",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Alani/Yellow Rassa",
                description: "Yellow curry with turmeric and spices",
                cost: 5.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Kolhapuri Mutton Tamda Rassa",
                description: "Red spicy mutton curry from Kolhapur",
                cost: 5.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kolhapuri Chicken Tamda Rassa",
                description: "Red spicy chicken curry from Kolhapur",
                cost: 5.99,
                spiceLevel: "spicy",
                region: "Kolhapur",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Kolhapuri Pandra Rassa",
                description: "White curry from Kolhapur",
                cost: 6.99,
                spiceLevel: "mild",
                region: "Kolhapur",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Rice",
        hideCategory: false,
        menuItems: [
            {
                title: "Chicken Pulav",
                description: "Fragrant basmati rice cooked with chicken and aromatic spices",
                cost: 14.99,
                spiceLevel: "medium",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: false,
                isNonVeg: true,
                isVegan: false
            },
            {
                title: "Plain Rice",
                description: "Steamed basmati rice",
                cost: 2.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            },
            {
                title: "Alani Rice",
                description: "Yellow rice with turmeric and spices",
                cost: 9.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Breads",
        hideCategory: false,
        menuItems: [
            {
                title: "Chapati",
                description: "Soft whole wheat flatbread",
                cost: 2.50,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            },
            {
                title: "Jowar Bhakari",
                description: "Traditional gluten-free sorghum flatbread, freshly made",
                cost: 3.50,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            }
        ]
    },
    {
        categoryTitle: "Sweets",
        hideCategory: false,
        menuItems: [
            {
                title: "Ice Cream",
                description: "Creamy ice cream",
                cost: 4.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Gulab Jamun",
                description: "Sweet milk dumplings in sugar syrup",
                cost: 4.99,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            }
        ]
    },
    {
        categoryTitle: "Beverages",
        hideCategory: false,
        menuItems: [
            {
                title: "Special Sarbat",
                description: "Traditional sweet drink",
                cost: 4.00,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            },
            {
                title: "Tea",
                description: "Hot tea",
                cost: 3.00,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            },
            {
                title: "Coffee",
                description: "Hot coffee",
                cost: 5.00,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            },
            {
                title: "Solkadhi",
                description: "Kokum-coconut digestive drink",
                cost: 5.00,
                spiceLevel: "mild",
                region: "Kolhapur",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Mango Lassi",
                description: "Sweet mango yogurt drink",
                cost: 5.00,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: false
            },
            {
                title: "Coke, Sprite, Diet Coke",
                description: "Soft drinks",
                cost: 2.00,
                spiceLevel: "mild",
                region: "Maharashtra",
                imageLink: "",
                videoLink: "",
                isDisplayed: true,
                hasModal: true,
                isSpeciality: false,
                isVeg: true,
                isNonVeg: false,
                isVegan: true
            }
        ]
    }
];
